### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by noxarivis** [orbitdb/orbit-web#10]
What is a Signal server?
"Signal Server Address
star-signal.cloud.ipfs.team"

**Comment by haadcode** [comment]
See https://github.com/ipfs/js-ipfs/issues/614.

It's essentially a way to find other peers in the IPFS network in the browser.

**Comment by diasdavid** [comment]
It is a rendezvous point to exchange signalling data and for [Peer Discovery](https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms).

**Comment by noxarivis** [comment]
@haadcode
How do i make an own signal server?

**Comment by haadcode** [comment]
@noxarivis follow the instructions on setting up a signal server from https://github.com/libp2p/js-libp2p-webrtc-star. Then change the orbit-web config here https://github.com/orbitdb/orbit-web/blob/master/src/config/ipfs-daemon.config.js#L16 to point to the locally running signalling server (127.0.0.1:13579 is the default).

Hope this helps!

**Comment by noxarivis** [comment]
Yup,
Perfect.
