### ISSUE TITLE
Browser's "waiting for ipfs.io..." tooltip blocks part of the type new message field (FF 68)

### ISSUE THREAD

**Issue by sirfumblestone** [orbitdb/orbit-web#108]
Version: https://gateway.pinata.cloud/ipfs/Qmdkcm63Y5MQnPYXht3D9RQnakpgHgJSiySqFusdsPD3a5
Browser: Firefox 68.0.2 (64-bit)
OS: Win10

Issue: Browser's "waiting for ipfs.io..." tooltip at the bottom left corner blocks the beginning of new message field. As a user I can't see what I've typed there.

![image](https://user-images.githubusercontent.com/37622336/64023108-46f02700-cb40-11e9-8e85-c9151d5e8cc5.png)

**Comment by latenssi** [comment]
That tooltip is native to the browser (cannot be altered by us) and fixing this issue would require moving the message input box somewhere else. Closing this issue for now.
