### ISSUE TITLE
Latest version pulled from repo broken

### ISSUE THREAD

**Issue by joeykrug** [orbitdb/orbit-web#109]
After entering a username the chat doesn't load on the latest build from this repo, it just does nothing

<img width="1517" alt="Screen Shot 2019-08-31 at 3 59 26 PM" src="https://user-images.githubusercontent.com/5925937/64069872-6488c380-cc08-11e9-8001-9493d599ad57.png">

**Comment by joeykrug** [comment]
Only thing in console is `Invalid asm.js: Unexpected token`

**Comment by haadcode** [comment]
Thanks for the issue @joeykrug! 

Would you be able to provide some more details as to what steps you took to launch the app? I just pulled the latest and I'm able to run it (clone repo, `npm install && npm run dev`). Were there any errors while installing or building the project?

The current version is up at https://gateway.pinata.cloud/ipfs/Qmdkcm63Y5MQnPYXht3D9RQnakpgHgJSiySqFusdsPD3a5 which you can give a try without running it from this repository. Does that work ok?

**Comment by RichardLitt** [comment]
Closing due to lack of response. Let us know if you've still got this, @joeykrug.
