### ISSUE TITLE
How is Orbit-Web not secure specifically?

### ISSUE THREAD

**Issue by JohnAllen** [orbitdb/orbit-web#11]
Is the IPFS gateway writable I'm guessing?  How else is this not secure?

**Comment by haadcode** [comment]
Orbit sends everything currently in plaintext and nothing is encrypted nor signed. 

And more generally, we haven't reviewed the code in terms of security, so essentially we can't make any security guarantees. Thus the big disclaimer in the readme.

Does that answer your question?

**Comment by JohnAllen** [comment]
Yes, yes it does, thank you.  If it's insecure in those ways it actually works fine for us because all our data is public anyways.
