### ISSUE TITLE
Uncaught Error: no protocol with name: p2p-webrtc-star

### ISSUE THREAD

**Issue by ido-ran** [orbitdb/orbit-web#13]
I've open https://orbit.chat in Chrome Version 62.0.3202.94 (Official Build) (64-bit)
on Windows 10 and this is the console output:

```
isElectron: false
app.js:87 Invalid asm.js: Type mismatch in assignment
app.js:167 Swarm listening on /libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss/ipfs/QmQbj14qMvwoXKsiEna6aWFvbLYh1NBtjF7Nq9atUFk7SE
60app.js:31 Uncaught Error: no protocol with name: p2p-webrtc-star
    at Protocols (app.js:31)
    at stringToStringTuples (app.js:255)
    at stringToBuffer (app.js:255)
    at Object.fromString (app.js:255)
    at new Multiaddr (app.js:6)
    at Multiaddr (app.js:6)
    at WebRTCStar._peerDiscovered (app.js:246)
    at Socket.Emitter.emit (app.js:71)
    at Socket.onevent (app.js:71)
    at Socket.onpacket (app.js:71)
```

**Comment by diasdavid** [comment]
@haadcode any hopes of giving some love to orbit-web?

**Comment by ztl8702** [comment]
Same issue here: 
  - OS: `Ubuntu 17.10 (64-bit)`
  - Browser: both `Firefox 58.0.2 (64-bit)` and `Chromium 64.0.3282.167` produce this error continuously in the console.  

Chromium and Firefox running locally can communicate with each other (peers = 1), but cannot find any other peers.

**Comment by ztl8702** [comment]
more logs:

![image](https://user-images.githubusercontent.com/2714446/37411978-29c5e1b6-27f8-11e8-98f4-af3d9da46481.png)

**Comment by harrshasri** [comment]
Same Issue Here

![error](https://user-images.githubusercontent.com/35241544/38229418-5752d4c4-36ce-11e8-8976-2b350c5ebfe9.png)

**Comment by SkyBeastMC** [comment]
same issue here on chrome 71

**Comment by aphelionz** [comment]
I believe we need to update `js-ipfs` to a newer version.

**Comment by evalsocket** [comment]
@aphelionz can we create a bigger issue for updating package.json with testing.`( js-ipfs, grunt-open,and all warnings )`
