### ISSUE TITLE
Certificate configured incorrectly

### ISSUE THREAD

**Issue by MatthewSteeples** [orbitdb/orbit-web#141]
![image](https://user-images.githubusercontent.com/255971/68213815-2f1ba000-ffd4-11e9-907a-0e61d26f5244.png)

The cert for https://orbit.chat is now configured to be *.dwebops.net which now refuses to load anything (as HSTS is configured)

**Comment by aphelionz** [comment]
cc @latenssi

**Comment by latenssi** [comment]
We were relying on gateway.ipfs.io's certificate which had orbit.chat in it. They changed it for some reason or something chanded atleast. We should do the HTML redirect "hack" talked about earlier since there is no other way to fix this as we use ipfs to host the app.

@aphelionz @vvp

**Comment by MatthewSteeples** [comment]
As an alternative (you only need to reconfigure the DNS) you could consider using Cloudflare's gateway. 

See the 3 steps at the bottom of https://www.cloudflare.com/distributed-web-gateway/ (step 3 is probably already done!)

**Comment by latenssi** [comment]
Ty @MatthewSteeples I used your proposed solution and it worked. orbit.chat is back online!
