### ISSUE TITLE
Please update to latest orbit-db

### ISSUE THREAD

**Issue by mohe2015** [orbitdb/orbit-web#150]
and also publish the new version on orbit.chat so https://github.com/orbitdb/orbit-web/commit/02c90befd410d5eb7d5a26cef27bb6c789dc0cf5 is also included.

That would be really appreciated.

**Comment by aphelionz** [comment]
@latenssi or @haadcode ?

**Comment by haadcode** [comment]
Orbit Chat is not a priority for me atm. and I won't be able to work on this.

Happy to accept a Pull Request that addresses this.

**Comment by x5engine** [comment]
this is broken and not working, please update
