### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by CleverSource** [orbitdb/orbit-web#17]
I had no clue what repo to put an idea in but I love the system going and want to see this turn into something bigger right now it seems like an IRC mainly but I want to see profile pictures, real accounts, email, calls, video calling, DMs, etc. Maybe turn this into something more than just a channel group chat app.

**Comment by RichardLitt** [comment]
Thanks, @CleverSource. There is certainly work to be done. If you're interested in helping out, I would suggest choosing some of the open issues and jumping in.
