### ISSUE TITLE
Orbit Chat is not getting past the loading screen 

### ISSUE THREAD

**Issue by divyansheccentric** [orbitdb/orbit-web#18]
I am running orbit chat on a development server but I never get past this screen...

![deepinscreenshot_select-area_20180327151157](https://user-images.githubusercontent.com/32994707/37959653-3ce5d17e-31d1-11e8-8ace-1693ed48e746.png)

When I checked the console for errors, it showed this...

![deepinscreenshot_select-area_20180327151211](https://user-images.githubusercontent.com/32994707/37959680-4bbe16d4-31d1-11e8-9e0e-ccd33351e738.png)

I don't know what the problem is. Please help.

**Comment by BernardJiang** [comment]
I saw the same error message after the following error on Chrome on Ubuntu. 

Uncaught TypeError: Cannot read property 'modules' of undefined
    at Object.<anonymous> (commons.js:189496)
    at Object.<anonymous> (commons.js:189687)
    at __webpack_require__ (commons.js:1333)
    at fn (commons.js:751)
    at Object.module.exports (commons.js:6290)
    at __webpack_require__ (commons.js:1333)
    at fn (commons.js:751)
    at Object.<anonymous> (commons.js:134888)
    at __webpack_require__ (commons.js:1333)
    at fn (commons.js:751)

This error came from webpack dependency spdy-transport:

// Node.js 0.8, 0.10 and 0.12 support
Object.assign = (process.versions.modules >= 46 || !isNode)
  ? Object.assign // eslint-disable-next-line
  : util._extend

It seems in case of web target (not node) for webpack.config.js, "process" has different definition from somewhere else, there is no "versions" in "process" that is supposed to be defined by Node. I found this error. But don't know how to fix it.  I tried the suggestion to change target to "Node" from "web" in webpack.config.js. It can't compile. I guess that is not the correct way to use orbit-web here. 

BTW, Orbit-electron works on my Ubuntu.

**Comment by BernardJiang** [comment]
HAHA, I actually hacked it. After changing the order of the questioned line to the following, both errors are gone. I can pass the loading screen now. A proper fix is still needed. 

orbit-web/node_modules/spdy-transport/lib/spdy-transport/utils.js

// Node.js 0.8, 0.10 and 0.12 support
Object.assign = ( !isNode || process.versions.modules >= 46)
  ? Object.assign // eslint-disable-next-line
  : util._extend
