### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dignifiedquire** [orbitdb/orbit-web#2]
I just tested the version at: https://ipfs.io/ipfs/QmbYfGVD34tM91Yu2bUDepTPb5XdB7qsR9oHhjqghwPo1e/#/channel/ipfs-dev and it through this error:

<img width="1168" alt="screen shot 2017-02-17 at 17 20 27" src="https://cloud.githubusercontent.com/assets/790842/23073369/9253ef12-f535-11e6-9b89-222536e9f81a.png">

**Comment by haadcode** [comment]
This was fixed in master.
