### ISSUE TITLE
No peers

### ISSUE THREAD

**Issue by moon004** [orbitdb/orbit-web#28]
When i browse https://orbit.chat, there seems to be no peer on channel #ipfs, since it is the only channel there, even after i started ipfs daemon on my command line, or am i getting things wrong here?

**Comment by aphelionz** [comment]
This is related to https://github.com/orbitdb/orbit-web/issues/13. I believe we need to update `js-ipfs` to a newer version.

**Comment by moon004** [comment]
Is there anything that i can help with? I'm really interested in this project.

**Comment by aphelionz** [comment]
The first thing to try would be to update js-ipfs to 0.33.1 and rebuild to see if that works. A lot of us are active on the gitter channel so you can reach out there.

**Comment by haadcode** [comment]
cc @latenssi who has been working on an updated version of basically the whole code base, would be helpful to sync (and see https://github.com/orbitdb/orbit-chat for where its at atm).

**Comment by r4de** [comment]
Hi,
before opening a new issue:
I'm trying to connect the orbit web-app over an mobile phone with orbit.chat, but no one can see/read me (0 peers).
By changing my mobile connection to wlan it works fine.

**Comment by RichardLitt** [comment]
Thanks, @r4de. We're working on rewriting this. We'll keep this use case in mind.

**Comment by latenssi** [comment]
@moon004 this issue should now be fixed in master branch. We are still in the process of updating the app running at https://orbit.chat to the latest version.

**Comment by moon004** [comment]
Alright great! i'm looking forward to it. Let me know when the latest version is live.

Thank you guys for your hard work!

**Comment by fCorleone** [comment]
So, anybody knows the reason about this issue?

**Comment by RichardLitt** [comment]
@aphelionz 	This is fixed, right? 

@fCorleone 	Can you update your version?

**Comment by aphelionz** [comment]
@latenssi I think this is fixed, please confirm?

**Comment by latenssi** [comment]
Closing as this has been fixed.
