### ISSUE TITLE
grunt-open is a security vulnerability

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-web#31]
Running `npm audit` in the current state results in a critical security vuln regarding `grunt-open`, which is also no longer maintained.

**Comment by aphelionz** [comment]
Looks like we could switch to https://github.com/sindresorhus/opn

**Comment by evalsocket** [comment]
@aphelionz did you check that [PR](https://github.com/jsoverson/grunt-open/pull/36) of grunt-open

**Comment by aphelionz** [comment]
Hmm, no I hadnt seen that. I wonder if this is even necessary or if we can simply yank out that code in this repo...

**Comment by evalsocket** [comment]
so what's next for that issue

**Comment by evalsocket** [comment]
@aphelionz please check [bug](https://snyk.io/node-js/grunt-open). Actually  npm package `open` is  vulnerable and  [PR](https://github.com/jsoverson/grunt-open/pull/36) Number 36 of grunt-open will resolve it. `open` or `opn` both use for open url but in `open` they didn't validate url and hacker can use exec().

**Comment by aphelionz** [comment]
Yes, I think we can replace it with https://github.com/sindresorhus/opn as I stated in a previous comment.
