### ISSUE TITLE
Add GitHub niceties to this repo

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-web#32]
- [x] Add issue template
- [x] Add PR template
- [x] Review README for compliance
- [x] Integreate tests and PRs with CircleCI

**Comment by evalsocket** [comment]
Review [ISSUE_TEMPLATE](https://github.com/evalsocket/orbit-web/blob/master/ISSUE_TEMPLATE.md) and [PULL_REQUEST_TEMPLATE](https://github.com/evalsocket/orbit-web/blob/master/PULL_REQUEST_TEMPLATE.md)

**Comment by evalsocket** [comment]
@aphelionz also add codeclimate config for all PR

**Comment by aphelionz** [comment]
Hadn't seen codeclimate! I'll check it out.

**Comment by RichardLitt** [comment]
I'm not sure we need the templates, for now, given the low-bandwidth of this repo. The README looks fine to me. 

How are tests and PRs going with CircleCI, @latenssi?

**Comment by latenssi** [comment]
@RichardLitt atm we do not have CircleCI integration in this repo.

**Comment by RichardLitt** [comment]
Aight. Should we keep this open?

**Comment by aphelionz** [comment]
I think @latenssi and @JaniAnttonen might want to get eyes on the PR and Issue templates that @evalsocket suggested. They might have more insight about what is / isn't needed there.  Other than that, I think it's good.

**Comment by RichardLitt** [comment]
Those look fine to me, but I think, given the low traffic in this repo at the moment, it's not really time for the templates yet. However, thank you, @evalsocket!

@latenssi if you agree, go ahead and close this. :)

**Comment by JaniAnttonen** [comment]
e2e tests added in #66
