### ISSUE TITLE
Change the text "peers" in the channel to "users"

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-web#5]
From Orbit:
```
14:48:03 peter is there a way to figure out how many users are online? (not peers)
14:49:29 Frank peter the UI is using React as the js framework, but if you mean visuals it's all custom. the "3 peers" box at the bottom-right corner tells you how many users are online on this channels atm.
14:49:45 Frank perhaps it should be "3 users" instead of "peers"
14:50:27 peter I assumed peers might mean connections, so there could be some that are mirroring everything, but aren't a user per se
14:50:59 peter I mean, connected orbit+ipfs instances
14:51:11 Frank ah ok, so that's confusing terminology then  :) because there's also the "Swarm" view that you can open from the panel that tells you the "peers in IPFS network"
```

I'd like try to a simple thing and change the text in the element that shows you how many peers are on this channel to say "3 users" instead of "3 peers". I believe that will avoid the confusion. 

Alternatively, change the text completely and use an icon (that says "people/users/online").

**Comment by prabodhmeshram** [comment]
@haadcode , Would like work on this. Can you provide a more info what need to be done here precisely .

**Comment by haadcode** [comment]
@prabodhmeshram thanks for signing up! :) 

This is as simple as changing "peers" to "users" in https://github.com/orbitdb/orbit-web/blob/facd2b5fc6919ada24d7e67bac6ef4c912d647ba/src/components/Channel.js#L470. I know this is super simple, but I wanted to leave this up for grabs for someone to make their first contribution :)

I can merge that to master easily but we won't be able to deploy it to orbit.chat just now as we're in the process of updating dependencies for orbit-web. But it'll end up there eventually :)
