### ISSUE TITLE
Where to use my localhost of Ipfs ? 

### ISSUE THREAD

**Issue by kesavananbu** [orbitdb/orbit-web#50]
I m using this deno and educational purpose it's working fine but i dont know to replace the localhost gateway of my ipfs. 

Is that possible to change the ipfs gateway ? 
Is that possible to use orbit-web without orbit-db because i dont need the old history. 

I need only the live chat can anyone help me  out guys ?

**Comment by aphelionz** [comment]
@kesavananbu i think what youre looking for is IPFS pubsub, which is the mechanism orbit-db uses for syncing and replication. Orbit-web is more or less a reference implementation for orbit-db and relies on database writes and replicate events for chat messaging.

I think if youre looking for just passing messages and not persisting them, try IPFS pubsub

**Comment by kesavananbu** [comment]
@aphelionz  Thanks for the Response. Ok then Is that possible to Make Create the Channel and Join the channel by specifying two buttons as Create and Join. When someone joins it should notify the channel created peer and only if we accepted he can join the chat.

**Comment by aphelionz** [comment]
Yes, what you're calling a channel is formally called a "topic." You can find ipfs pubsub docs here: https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/PUBSUB.md

Beware: alpha software, YMMV

**Comment by kesavananbu** [comment]
Thanks @aphelionz  for your response.
