### ISSUE TITLE
Each time creates new User ?

### ISSUE THREAD

**Issue by kesavananbu** [orbitdb/orbit-web#53]
I would like to use the user who already been ? Is that possible to use the user who got in ?  
But it creates each time new user ? And then inside in login page Configuration not working after running dev. How to use the Login with Uport ?

**Comment by JaniAnttonen** [comment]
Hello!

Uport has been disabled in this project, and the configure button is still non-functional at this point.  Additionally, the domain orbit.chat has an older version of orbit-web running at the moment, and we are in the progress of updating it.

User names are not unique, and the private keys are browser-based and saved in the browser's `localStorage`. This means that at this point in time, the user's state is not synchronisable between browsers/devices unless you copy the user settings from the `localStorage` to another browser.

**Comment by kesavananbu** [comment]
Hi @JaniAnttonen  Thank you for the response. Could you help me fetch the user setting from the browser and to migrate to another browser is there any way ? Could you help me out ?

**Comment by JaniAnttonen** [comment]
Follow-up in #70
