### ISSUE TITLE
Blocking User option Needed ? Current Peers Name List 

### ISSUE THREAD

**Issue by kesavananbu** [orbitdb/orbit-web#54]
I need to explicitly block user to chat with me. Is there any possibility?

Is there way to view the Online Peers list instead of clicking on the peers?

**Comment by latenssi** [comment]
Currently there is no way of blocking a user from chatting with you. Anybody can join any channel and everybody has read and write access. There are plans to implement the ability to have channels for which only certain users have write access and everyone has read access.

Regarding the peer list, currently we only have a list of IPFS peer Id's which are basically just multihashes ("Qma63TiX691SSa5Yvd37TH8pcrevZ9EJ12JtWRYPRpin3W") and I don't think that is associated in any way with an orbit user. @shamb0t and @aphelionz might have better understanding of the IPFS peer id.

**Comment by aphelionz** [comment]
Thanks @latenssi. There is currently no direct way to get orbit addresses if you only know the peer id.

**Comment by kesavananbu** [comment]
Thanks @latenssi  and @aphelionz  for the response and providing me the information.
