### ISSUE TITLE
Add fallback to video preview for files that don't support streaming

### ISSUE THREAD

**Issue by kesavananbu** [orbitdb/orbit-web#62]
Hi Team, There is a problem with Video Preview when i tried to load the preview the video it just loads some time loading screen and not playing anything. May i know whats the issue.

**Comment by JaniAnttonen** [comment]
Hello! What kind of video were you trying to play? Due to limitations in the browser streaming APIs there's only the possibility to preview fragmented mp4 and webm files. There might be some ways around this limitation though.

**Comment by kesavananbu** [comment]
Fragmented mp4 means what ?

I m trying play to normal mp4. 

Why is that not possible ?

**Comment by JaniAnttonen** [comment]
Normal .mp4 files don't work because the app is trying to stream them and they don't support streaming. There should be a fallback for playing back the whole file at once.
