### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by daxdax89** [orbitdb/orbit-web#78]
I've cloned orbit web repo inside Amazon EC2 Ubuntu 18 instance. Did a npm install and after i did npm run build i've got:

BrowserslistError: Unknown browser query `android all`

What's the issue with this?

**Comment by JaniAnttonen** [comment]
This is most probably related to https://github.com/ben-eb/caniuse-lite/issues/27. Please try to run npm install agaIn, it should work now.

**Comment by latenssi** [comment]
Closing as this seems fixed in latest version.
