### ISSUE TITLE
Crash "Objects are not valid as a React child"

### ISSUE THREAD

**Issue by SnowyCoder** [orbitdb/orbit-web#84]
Hello, as the site `orbit.chat` is not working I tried to download the code and run it myself, after some messages the app crashed along with any page refresh that I tried.
Those are the logs of a page crash:

https://pastebin.com/kJFR7Zrf

**Comment by latenssi** [comment]
Hello! I think the pastebin has expired or something as it is "private". Can you try again and capture a log?

**Comment by SnowyCoder** [comment]
Ops, my mystake.
Paste exposure fixed

**Comment by latenssi** [comment]
Thank you! I think that problem is caused by a version mismatch somewhere. The dependency tree of orbit-web has been quite lively so these happen. 

Can you pull the #86 (feat/web-worker) branch and try a fresh install?

**Comment by latenssi** [comment]
I just got this same error on my build so it is not about dependency mismatch. I need to investigate this more.

**Comment by latenssi** [comment]
Yea this seems to happen on "orbitdb" channel but not on others so on that channel there must be a message that breaks the app.
