### ISSUE TITLE
dragging highlighted text breaks app

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-web#95]
if you highlight and drag text while in a chat it brings up a prompt to upload files to ipfs that you cant escape without reload.

**Comment by latenssi** [comment]
@tabcat Confirmed. Thank you for reporting this!

**Comment by latenssi** [comment]
For some reason this seems to have been fixed on its own. Can you confirm with the latest version from master @tabcat?

**Comment by tabcat** [comment]
@latenssi Confirmed in deployed version. Shows prompt to upload files to ipfs that goes away when you stop dragging.
